dist: trusty
notifications:
  email: false
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR

env:
  global:
    - CC_TEST_REPORTER_ID=747d8a7fc1700cea5c7e07aba5de7a70acd6a695c7ff481852bbcf95c3f1086c

addons:
 apt:
  packages:
    - build-essential # everything
    - zlib1g-dev # many
    - libcurl4-openssl-dev # many
    - unzip # kentools/pcap
    - libcairo2-dev # give png.h for kentsrc and used by R in later components
    - time
    - curl

before_install:
    - sudo add-apt-repository "deb https://cran.ma.imperial.ac.uk/bin/linux/ubuntu trusty/"
    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
    - sudo apt-get update
    - sudo apt-get install r-base

language: python

python: 
    - "3.6"

install:
  - pip install --upgrade setuptools  # to avoid egg_info erro code 1 exit
  - pip install pytest
  - pip install pytest-cover
  - pip install pandas
  - pip install numpy
  - pip install plotly
  - pip install .

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - cd Rsupport
  - printenv
  - sudo ./setupR.sh /home/travis/build/cancerit/pyCRISPRcleanR
  - cd ../
  - wget https://pypi.python.org/packages/7d/3e/48954b03db340b6f0be31e2f49f562a21bc9e0dcfa2cb7eba99ee0e11a47/rpy2-2.9.2.tar.gz#md5=05d0b5c79b3f6cfada2560a269dc95ba
  - tar -xzf rpy2-2.9.2.tar.gz 
  - cd rpy2-2.9.2
  - python setup.py build --r-home $R_LIBS install
  - cd ..
  - pytest --cov-report term --cov-report xml --cov-fail-under=50 --cov=pyCRISPRcleanR
  - coverage xml

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
